# Generated by fusen: do not edit by hand

# Temporary directory for reproducible example
dir_tmp <- tempfile(pattern = "proj-")
dir.create(dir_tmp)

file.copy(from = system.file("examples/example_rmd.Rmd", package = "odsrmd"), to = dir_tmp)
file.copy(from = system.file("examples/style.css", package = "odsrmd"), to = dir_tmp)
file.copy(from = system.file("examples/example_rmd_wo_css.Rmd", package = "odsrmd"), to = dir_tmp)
file.copy(from = system.file("examples/example_flexdashboard.Rmd", package = "odsrmd"), to = dir_tmp)
file.copy(from = system.file("examples/example_pagedown.Rmd", package = "odsrmd"), to = dir_tmp)
# browseURL(dir_tmp)
path1 <- paste0(dir_tmp, "/example_rmd.Rmd")
path2 <- paste0(dir_tmp, "/example_rmd_wo_css.Rmd")
path3 <- paste0(dir_tmp, "/example_flexdashboard.Rmd")
path4 <- paste0(dir_tmp, "/example_pagedown.Rmd")

output <- get_body_and_style(path1)

test_that("get_body_and_style works", {
  expect_true(inherits(get_body_and_style, "function"))
  expect_type(output, "list")
  expect_length(output, 2)
  expect_identical(names(output), c("body", "style"))
  expect_error(get_body_and_style(path1, add_extra_css = ""))
  expect_error(get_body_and_style(path2, add_extra_css = "append"))
  expect_error(get_body_and_style(path3))
  expect_error(get_body_and_style(path4))
})
