# Generated by fusen: do not edit by hand

test_that("get_ods_page works", {
  # expect_true(inherits(get_ods_page, "function"))
  vcr::use_cassette("get_ods_page", {
    page_content <- get_ods_page(page_slug = "test")
  })

  testthat::expect_type(page_content, "list")
  testthat::expect_length(page_content, 13)

})

test_that("get_ods_page detects invalid slug", {
  testthat::expect_error(get_ods_page(page_slug = ""))

})




