# Generated by fusen: do not edit by hand

# Temporary directory for reproducible example
dir_tmp <- tempfile(pattern = "proj-")
dir.create(dir_tmp)

file.copy(from = system.file("examples/example_rmd.Rmd", package = "odsrmd"), to = dir_tmp)
file.copy(from = system.file("examples/style.css", package = "odsrmd"), to=dir_tmp)
# browseURL(dir_tmp)
path <- paste0(dir_tmp, "/example_rmd.Rmd")
page_slug <- "odsrmd-example"

resp <- update_ods_page(path, page_slug, add_extra_css = "no", chosen_languages = "all", title = NULL,
  description = NULL, tags = NULL, restricted = NULL
)


test_that("update_ods_page works", {
  expect_true(inherits(update_ods_page, "function")) 
  expect_equal(resp$status, 200)
    expect_error(update_ods_page(path, page_slug, chosen_languages = "", title = NULL,
  description = NULL, tags = NULL, restricted = NULL
))
  expect_message(update_ods_page(path, page_slug, chosen_languages = "all", title = NULL,
  description = NULL, tags = NULL, restricted = NULL
))
})
