# Generated by fusen: do not edit by hand

# Temporary directory for reproducible example
dir_tmp <- tempfile(pattern = "proj-")
dir.create(dir_tmp)

file.copy(from = system.file("examples/example_rmd.Rmd", package = "odsrmd"), to=dir_tmp)
file.copy(from = system.file("examples/style.css", package = "odsrmd"), to=dir_tmp)
# browseURL(dir_tmp)
path <- paste0(dir_tmp, "/example_rmd.Rmd")

css_output <- add_css(path)

test_that("add_css works", {
  expect_true(inherits(add_css, "function")) 
  expect_type(css_output, "character")
})
