# Generated by fusen: do not edit by hand

page_slug <- "odsrmd-example"
page_elements <- get_ods_page(page_slug)

all_languages <- get_languages(page_elements)

test_that("get_languages works", {
  expect_true(inherits(get_languages, "function"))
  expect_type(all_languages, "character")
  expect_message(get_languages(page_elements))
  expect_silent(get_languages(page_elements, verbose = FALSE))
})
