# Generated by fusen: do not edit by hand

page_slug <- "testthat-odsrmd" 
page_elements <- get_ods_page(page_slug)

test_that("is_available works", {
  expect_true(inherits(is_available, "function"))
  expect_error(is_available("randomword", page_elements))
  expect_silent(is_available("EN", page_elements))
})
