# Generated by fusen: do not edit by hand

# Temporary directory for reproducible example
dir_tmp <- tempfile(pattern = "proj-")
dir.create(dir_tmp)

file.copy(from = system.file("examples/example_rmd.Rmd", package = "odsrmd"), to=dir_tmp)
# browseURL(dir_tmp)
path <- paste0(dir_tmp, "/example_rmd.Rmd")

output <- get_body_and_style(path)

test_that("get_body_and_style works", {
  expect_true(inherits(get_body_and_style, "function"))
  expect_type(output, "list")
  expect_length(output, 2)
})
