# Generated by fusen: do not edit by hand

#' Identify extra css file(s) from Rmd files
#' 
#' Identify css files listed in Rmarkdown yaml (output: html_document: css: ...) and concatenate them in a single character string. 
#' 
#' @param path Path to the Rmd file. 
#'
#' @return A character string. 
#' @importFrom rmarkdown yaml_front_matter
#' 
#' @noRd
#' @examples
#' # Temporary directory for reproducible example
#' dir_tmp <- tempfile(pattern = "proj-")
#' dir.create(dir_tmp)
#' 
#' file.copy(from = system.file("examples/example_rmd.Rmd", package = "odsrmd"), to=dir_tmp)
#' file.copy(from = system.file("examples/style.css", package = "odsrmd"), to=dir_tmp)
#' # browseURL(dir_tmp)
#' path <- paste0(dir_tmp, "/example_rmd.Rmd")
#' 
#' add_css(path)
add_css <- function(path){
    yaml_tmp <- yaml_front_matter(path)
    css_files <- yaml_tmp$output$html_document$css
    
    css_content <- map_chr(css_files, function(x){
      file_tmp <- file.path(dirname(path), x) 
      readLines(con = file_tmp) %>% 
        glue_collapse(sep = "\n")
    })
    
    glue_collapse(css_content, sep = "\n")
}
