# Generated by fusen: do not edit by hand

#' Extract error messages and warnings sent by the API
#'
#' @param resp A response object. 
#'
#' @return The message and error parts from the content-type header. 
#' @importFrom httr2 resp_body_json
#' @importFrom purrr map_chr pluck
#' @noRd
#' @examples
#' \dontrun{
#' library(httr2)
#' 
#' ods_domain_id <- Sys.getenv("ODS_DOMAIN_ID")
#' ods_username <- Sys.getenv("ODS_USERNAME")
#' ods_password <- Sys.getenv("ODS_PASSWORD")
#' 
#' domain_url <- paste0("https://", ods_domain_id, ".opendatasoft.com/api/management/v2/")
#' page_slug <- "testthat-odsrmd"
#' 
#' resp <- request(domain_url) %>%
#'   req_auth_basic(username = ods_username, password = ods_password) %>%
#'   req_url_path_append("p", page_slug) %>%
#'   req_user_agent("R package odsrmd") %>%
#'   req_perform()
#' 
#' api_error_body(last_response())
#' }
api_error_body <- function(resp) {
  resp_tmp <- resp %>%
    resp_body_json() 
  
  if (!is.null(resp_tmp$message)){
    message <- resp_tmp$message
  }else{
    message <- ""
  }
  
  if (!is.null(resp_tmp$error)){
    error <- resp_tmp$error
  }else{
    error <- ""
  }
  
  if (!is.null(resp_tmp$errors)){
    
    detailed_errors <- map_chr(length(resp_tmp$errors), function(x){
      error_keys <- pluck(resp_tmp, "errors", 1, "error_key")
      error_messages <- pluck(resp_tmp, "errors", 1, "message")
      paste(error_keys, error_messages, sep = "\n")
    }
    )
  }else{
    detailed_errors <- ""
  }
  
  message(paste(error, message, detailed_errors, sep = "\n"))
}
