# Generated by fusen: do not edit by hand

#' Identify extra css file(s) from Rmd files
#' 
#' Identify css files listed in Rmarkdown yaml (output: html_document: css: ...) and concatenate them in a single character string. 
#' 
#' @param path Path to the Rmd file. 
#'
#' @return A character string. 
#' @importFrom rmarkdown yaml_front_matter
#' 
#' @noRd
#' @examples
#' \dontrun{
#' # Temporary directory for reproducible example
#' #'
#' dir_tmp <- tempfile(pattern = "proj-")
#' dir.create(dir_tmp)
#' #'
#' file.copy(from = system.file("examples/example_rmd.Rmd", package = "odsrmd"), to=dir_tmp)
#' file.copy(from = system.file("examples/style.css", package = "odsrmd"), to=dir_tmp)
#' # browseURL(dir_tmp)
#' path <- paste0(dir_tmp, "/example_rmd.Rmd")
#' #'
#' add_css(path)
#' }
add_css <- function(path) {
  yaml_tmp <- yaml_front_matter(path)
  css_files <- yaml_tmp$output$html_document$css

  css_content <- map_chr(css_files, function(x) {
    file_tmp <- file.path(dirname(path), x)
    readLines(con = file_tmp) %>%
      glue_collapse(sep = "\n")
  })

  glue_collapse(css_content, sep = "\n")
}

#' Extract error messages and warnings sent by the API
#'
#' @param resp A response object. 
#'
#' @return The message and error parts from the content-type header. 
#' @importFrom httr2 resp_body_json
#' @importFrom purrr map_chr pluck
#' @noRd
#' @examples
#' \dontrun{
#' library(httr2)
#' 
#' ods_domain_id <- Sys.getenv("ODS_DOMAIN_ID")
#' ods_username <- Sys.getenv("ODS_USERNAME")
#' ods_password <- Sys.getenv("ODS_PASSWORD")
#' 
#' domain_url <- paste0("https://", ods_domain_id, ".opendatasoft.com/api/management/v2/")
#' page_slug <- "testthat-odsrmd"
#' 
#' resp <- request(domain_url) %>%
#'   req_auth_basic(username = ods_username, password = ods_password) %>%
#'   req_url_path_append("p", page_slug) %>%
#'   req_user_agent("R package odsrmd") %>%
#'   req_perform()
#' 
#' api_error_body(last_response())
#' }
api_error_body <- function(resp) {
  resp_tmp <- resp %>%
    resp_body_json() 
  
  if (!is.null(resp_tmp$message)){
    message <- resp_tmp$message
  }else{
    message <- ""
  }
  
  if (!is.null(resp_tmp$error)){
    error <- resp_tmp$error
  }else{
    error <- ""
  }
  
  if (!is.null(resp_tmp$errors)){
    
    detailed_errors <- map_chr(length(resp_tmp$errors), function(x){
      error_keys <- pluck(resp_tmp, "errors", 1, "error_key")
      error_messages <- pluck(resp_tmp, "errors", 1, "message")
      paste(error_keys, error_messages, sep = "\n")
    }
    )
  }else{
    detailed_errors <- ""
  }
  
  message(paste(error, message, detailed_errors, sep = "\n"))
}
