# Generated by fusen: do not edit by hand

#' Create JSON element to send to ODS platform.   
#' 
#' Combine information coming from the Opendatasoft page (with get_ods_page()) and the Rmarkdown document (with get_body_and_style()) into a JSON object ready to be sent back to the Opendatasoft platform.
#' 
#' @param page_elements List object from get_page(). Contains the title, description, template, language, content, tags and level of restriction of the page. By default, if no value is provided to title, description, template, language, tags and restricted, create_json() takes the values available in page_elements.    
#' @param body_and_style List object containing body and style of knitted Rmd document coming from get_body_and_style().     
#' @param title A character string specifying the title of the page. If not null, overwrites title from page_elements. 
#' @param description A character string containing the description of the page. If not null, overwrites description from page_elements. 
#' @param template The template of the page. Default to "custom.html". If not null, overwrites template from page_elements. 
#' @param language The language in which you would like to post the page. It should be one of the languages available on the Opendatasoft platform. hosting the page. 
#' @param tags A list object of character strings containing the tags describing the page. If not null, overwrites tags from page_elements. 
#' @param restricted A boolean TRUE/FALSE indicating the reading status of the page. TRUE will make the page "public" whereas FALSE will keep its access restricted to users who where granted the permission. If not null, overwrites reading status from page_elements.     
#'
#' @return a JSON element  
#' @importFrom jsonlite toJSON
#' 
#' @export
#' @examples
#' # Temporary directory for reproducible example
#' dir_tmp <- tempfile(pattern = "proj-")
#' dir.create(dir_tmp)
#' 
#' file.copy(from = system.file("examples/example_rmd.Rmd", package = "odsrmd"), to=dir_tmp)
#' # browseURL(dir_tmp)
#' path <- paste0(dir_tmp, "/example_rmd.Rmd")
#' 
#' body_and_style <- get_body_and_style(path)
#' 
#' 
#' page_elements <- get_ods_page(page_slug = "test")
#' 
#' create_json(page_elements, body_and_style, language = NULL, 
#'                         title = NULL, description = NULL, template = NULL, 
#'                         tags = NULL, restricted = NULL)
create_json <- function(page_elements, body_and_style,
                        title = NULL, description = NULL, template = NULL,
                        language = NULL, tags = NULL, restricted = NULL) {
  JSONlist <- list()

    if (is.null(language)) {
    language <- names(page_elements$content$html)[1]
  }
  
  # Add title
  if (is.null(title)) {
    JSONlist$title[[language]] <- page_elements$title[[language]]
  } else {
    JSONlist$title[[language]] <- title
  }

  # Add description
  if (is.null(description)) {
    JSONlist$description <- page_elements$description
  } else {
    JSONlist$description <- description
  }

  # Add template
  if (is.null(template)) {
    JSONlist$template <- page_elements$template
  } else {
    JSONlist$template <- template
  }

  # Add content
  JSONlist$content$html[[language]] <- body_and_style$body
  JSONlist$content$css[[language]] <- body_and_style$style
  # purrr::pluck(.x = page_elements, "content", "css", language) <- body_and_style$style

  # Add tags
  if (is.null(tags)) {
    JSONlist$tags <- page_elements$tags
  } else {
    JSONlist$tags <- tags
  }

  # Add restricted
  if (is.null(restricted)) {
    JSONlist$restricted <- page_elements$restricted
  } else {
    JSONlist$restricted <- restricted
  }

  toJSON(JSONlist, auto_unbox = TRUE)
}

