# Generated by fusen: do not edit by hand

#' Get ODS page
#' 
#' Get the content of an ODS page.   
#' 
#' @param page_slug Slug of the page. 
#'
#' @return A list object containing the information from the page. 
#' @importFrom httr2 request req_auth_basic req_url_path_append req_user_agent req_perform resp_body_json
#' 
#' @export
#' @examples
#' get_ods_page(page_slug = "test")
#' 
get_ods_page <- function(page_slug) {
  ods_domain_id <- Sys.getenv("ODS_DOMAIN_ID")
  ods_username <- Sys.getenv("ODS_USERNAME")
  ods_password <- Sys.getenv("ODS_PASSWORD")

  domain_url <- paste0("https://", ods_domain_id, ".opendatasoft.com/api/management/v2/")

  resp <- request(domain_url) %>%
    req_auth_basic(username = ods_username, password = ods_password) %>%
    req_url_path_append("pages", page_slug) %>%
    req_user_agent("R package odsrmd") %>%
    req_error(body = api_error_body) %>%
    req_perform()

  resp %>% resp_body_json()
}

