# Generated by fusen: do not edit by hand

#' Get ODS page
#' 
#' Get the content of a classic page from an Opendatasoft platform.   
#' 
#' @param page_slug Slug of the page (in the backoffice of the platform -> Pages -> New or existing page -> Properties -> Page URL). 
#'
#' @return A list object containing the information from the page (title, description, tags...). 
#' @importFrom httr2 request req_auth_basic req_url_path_append req_user_agent req_error req_perform resp_body_json
#' 
#' @export
#' @examples
#' page_slug <- "odsrmd-example" 
#' page_elements <- get_ods_page(page_slug) 
#' 
get_ods_page <- function(page_slug) {
  if (page_slug == "") {
    stop(
      "Please provide a unique page slug\n",
      'With "", you are trying to query all pages at the same time!'
    )
  }

  ods_domain_id <- Sys.getenv("ODS_DOMAIN_ID")
  ods_username <- Sys.getenv("ODS_USERNAME")
  ods_password <- Sys.getenv("ODS_PASSWORD")

  if (ods_domain_id == "") {
    stop(
      "The domain identifier of the Opendatasoft platform is missing.\n",
      "Please add the environmental variable ODS_DOMAIN_ID to your .Renviron file with the corresponding domain identifier.\n",
      "Reminder, your domain identifier is part of your domain URL : https://your_domain_ID.opendatasoft.com/"
    )
  }

  if (ods_username == "") {
    stop(
      "Your username is missing.\n",
      "Please add the environmental variable ODS_USERNAME to your .Renviron file with the corresponding username.\n"
    )
  }

  if (ods_password == "") {
    stop(
      "Your password is missing.\n",
      "Please add the environmental variable ODS_PASSWORD to your .Renviron file with the corresponding password\n"
    )
  }

  domain_url <- paste0("https://", ods_domain_id, ".opendatasoft.com/api/management/v2/")

  resp <- request(domain_url) %>%
    req_auth_basic(username = ods_username, password = ods_password) %>%
    req_url_path_append("pages", page_slug) %>%
    req_user_agent("R package odsrmd") %>%
    req_error(body = api_error_body) %>%
    req_perform()

  resp %>% resp_body_json()
}

