# Generated by fusen: do not edit by hand

#' Get body and style
#' 
#' Extract the nodes corresponding to body and style without the script nodes.    
#' 
#' @param path Path to Rmd file. 
#'
#' @return A named list with two elements : body and style. 
#' @importFrom rmarkdown render
#' @importFrom rvest read_html html_elements html_text html_nodes
#' @importFrom glue glue_collapse
#' @importFrom magrittr %>%
#' 
#' @export 
#' @examples
#' # Temporary directory for reproducible example
#' dir_tmp <- tempfile(pattern = "proj-")
#' dir.create(dir_tmp)
#' 
#' file.copy(from = system.file("data/example_rmd.Rmd", package = "odsrmd"), to=dir_tmp)
#' # browseURL(dir_tmp)
#' path <- paste0(dir_tmp, "/example_rmd.Rmd")
#' 
#' get_body_and_style(path)
get_body_and_style <- function(path) {
  render(path, output_format = "html_document", output_options = "self-contained", envir = new.env())

  path_html <- gsub(pattern = ("[.]rmd|[.]Rmd"), replacement = ".html", x = path)

  html_content <- read_html(path_html)
  style <- html_elements(html_content, "style") %>%
    html_text() %>%
    glue_collapse()

  body <- rvest::html_elements(html_content, "body>:not(script)") %>%
    glue_collapse()

  list(body = body, style = style)
}
