# Generated by fusen: do not edit by hand

#' Check language availability
#' 
#' Check if a given language is available on the ODS platform from the list of languages contained in page_elements. 
#' 
#' @param language Character string. 
#' @param page_elements List object from get_page(). Contains the title, description, template, language, content, tags and level of restriction of the page. 
#'
#' @importFrom glue glue
#' 
#' @export
#' @examples
#' page_slug <- "testthat-odsrmd" 
#' page_elements <- get_ods_page(page_slug) 
#' 
#' is_available("EN", page_elements)
is_available <- function(language, page_elements) {
  if (!tolower(language) %in% get_languages(page_elements, verbose = FALSE)) {
    stop(
      glue("Language '{language}' is not available on the platform. To add more languages to your platform, please contact your administrator or Opendatasoft support.")
    )
  }
}
