# Generated by fusen: do not edit by hand

#' Put ODS page
#' 
#' Send JSON element to a page from an Opendatasoft platform.  
#' 
#' @param page_slug  Slug of the page (in the backoffice of the platform -> Pages -> New or existing page -> Properties -> Page URL).    
#' @param json_to_send JSON object containing page information, such as title, description, content and tags, that put_ods_page() sends on the page corresponding to the page slug.     
#' @importFrom httr2 request req_auth_basic req_url_path_append req_user_agent req_method req_body_raw req_error req_perform req_options
#'
#' @return If request is successful (i.e. the request was successfully performed and a response with HTTP status code <400 was received), an HTTP response; otherwise it throws an error. 
#' 
#' @export
#' @examples
#' # Temporary directory for reproducible example
#' dir_tmp <- tempfile(pattern = "proj-")
#' dir.create(dir_tmp)
#' 
#' file.copy(from = system.file("examples/example_rmd.Rmd", package = "odsrmd"), to=dir_tmp)
#' file.copy(from = system.file("examples/style.css", package = "odsrmd"), to=dir_tmp)
#' # browseURL(dir_tmp)
#' path <- paste0(dir_tmp, "/example_rmd.Rmd")
#' page_slug <- "testthat-odsrmd"
#' 
#' 
#' body_and_style <- get_body_and_style(path)
#' 
#' 
#' page_elements <- get_ods_page(page_slug)
#' 
#' json_to_send <- create_json(page_elements, body_and_style, chosen_languages = c("en", "fr"), 
#'                         title = "English title", description = NULL,  
#'                         tags = NULL, restricted = NULL)
#' 
#' put_ods_page(page_slug, json_to_send)
#' 
#' 
put_ods_page <- function(page_slug, json_to_send) {
  if (page_slug == "") {
    stop(
      "Please provide a valid page slug."
    )
  }

  if (class(json_to_send) != "json") {
    stop(
      "json_to_send must be of class 'json'."
    )
  }

  ods_domain_id <- Sys.getenv("ODS_DOMAIN_ID")
  ods_username <- Sys.getenv("ODS_USERNAME")
  ods_password <- Sys.getenv("ODS_PASSWORD")

  if (ods_domain_id == "") {
    stop(
      "The domain identifier of the Opendatasoft platform is missing.\n",
      "Please add the environmental variable ODS_DOMAIN_ID to your .Renviron file with the corresponding domain identifier.\n",
      "Reminder, your domain identifier is part of your domain URL : https://your_domain_ID.opendatasoft.com/"
    )
  }

  if (ods_username == "") {
    stop(
      "Your username is missing.\n",
      "Please add the environmental variable ODS_USERNAME to your .Renviron file with the corresponding username.\n"
    )
  }

  if (ods_password == "") {
    stop(
      "Your password is missing.\n",
      "Please add the environmental variable ODS_PASSWORD to your .Renviron file with the corresponding password\n"
    )
  }


  domain_url <- paste0("https://", ods_domain_id, ".opendatasoft.com/api/management/v2/")

  resp <- request(domain_url) %>%
    req_auth_basic(username = ods_username, password = ods_password) %>%
    req_url_path_append("pages", page_slug) %>%
    req_user_agent("R package odsrmd") %>%
    req_method("PUT") %>%
    req_body_raw(json_to_send) %>%
    req_error(body = api_error_body) %>%
    req_perform()

  resp
}

