# Generated by fusen: do not edit by hand

#' Put ODS page
#' 
#' Send JSON element to an ODS page.  
#' 
#' @param page_slug  Slug of the page.
#' @param json_to_send JSON object that will be send to the Opendatasoft portal and which information will be displayed on the page corresponding to the page slug.   
#' @importFrom httr2 request req_auth_basic req_url_path_append req_user_agent req_method req_body_raw req_error req_perform req_options
#'
#' @return If request is successful (i.e. the request was successfully performed and a response with HTTP status code <400 was received), an HTTP response; otherwise throws an error. 
#' 
#' @export
#' @examples
#' 
#' # Temporary directory for reproducible example
#' dir_tmp <- tempfile(pattern = "proj-")
#' dir.create(dir_tmp)
#' 
#' file.copy(from = system.file("data/example_rmd.Rmd", package = "odsrmd"), to=dir_tmp)
#' # browseURL(dir_tmp)
#' path <- paste0(dir_tmp, "/example_rmd.Rmd")
#' 
#' body_and_style <- get_body_and_style(path)
#' 
#' 
#' page_elements <- get_ods_page(page_slug = "test")
#' 
#' json_to_send <- create_json(page_elements, body_and_style, language = NULL, 
#'                         title = NULL, description = NULL, template = NULL, 
#'                         tags = NULL, restricted = NULL)
#' page_slug <- "test"
#' 
#' put_ods_page(page_slug, json_to_send)
#' 
#' 
put_ods_page <- function(page_slug, json_to_send) {
  ods_domain_id <- Sys.getenv("ODS_DOMAIN_ID")
  ods_username <- Sys.getenv("ODS_USERNAME")
  ods_password <- Sys.getenv("ODS_PASSWORD")
  domain_url <- paste0("https://", ods_domain_id, ".opendatasoft.com/api/management/v2/")

  resp <- request(domain_url) %>%
    req_auth_basic(username = ods_username, password = ods_password) %>%
    req_url_path_append("pages", page_slug) %>%
    req_user_agent("R package odsrmd") %>%
    req_method("PUT") %>%
    req_body_raw(json_to_send) %>%
    req_error(body = api_error_body) %>%
    req_perform()

  resp

}

